[[actions]]
action = "file.remove"
target = "~/.config/nvim/*"

action = "file.link"
from = "./nvim/*"
to = "~/.config/nvim"

action = "file.remove"
target = "~/.config/kitty/*"

action = "file.link"
from = "./kitty/*"
to = "~/.config/kitty/"

action = "file.remove"
target = "~/.config/wofi/*"

action = "file.link"
from = "./wofi/*"
to = "~/.config/wofi/"

action = "file.remove"
target = "~/.config/waybar/*"

action = "file.link"
from = "./waybar/*"
to = "~/.config/waybar/"

action = "file.link"
from = "./colors/*"
to = "~/.config/colors/"

action = "file.remove"
target = "~/.config/hypr/*"

action = "file.link"
from = "./hyprland/*"
to = "~/.config/hypr/"

